baseURL = "https://blog.avahe.tk"
languageCode = "en-us"
title = "Avahe's Blog"
theme = "m10c"

[params]
  author = "Avahe Kellenberger"
  description = "My blog about things"
  avatar = "avatar.jpg"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#f5e3e0"
  lightestColor = "#ffffff"
  primaryColor = "#56cb89"

[[params.social]]
  name = "github"
  url = "https://github.com/avahe-kellenberger"

[[params.social]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCqX8ZNI7rfx9QiF5Lrnv6kg"

